// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEwwYGGdbTorhKQC9z22mtuK1MBW3D1bQ',
    appId: '1:1006899144467:web:10aecad224c3cda5555ce6',
    messagingSenderId: '1006899144467',
    projectId: 'navasanganakah',
    authDomain: 'navasanganakah.firebaseapp.com',
    databaseURL: 'https://navasanganakah-default-rtdb.firebaseio.com',
    storageBucket: 'navasanganakah.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBnwhTTM3w8aiXHxC_4rX6aonhIe3wjqo',
    appId: '1:1006899144467:android:843ba3b9660eb460555ce6',
    messagingSenderId: '1006899144467',
    projectId: 'navasanganakah',
    databaseURL: 'https://navasanganakah-default-rtdb.firebaseio.com',
    storageBucket: 'navasanganakah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPhHcW6URI7vGLACsLQtPkfaTv5Q-DdBY',
    appId: '1:1006899144467:ios:5f94936bfba1f605555ce6',
    messagingSenderId: '1006899144467',
    projectId: 'navasanganakah',
    databaseURL: 'https://navasanganakah-default-rtdb.firebaseio.com',
    storageBucket: 'navasanganakah.firebasestorage.app',
    androidClientId: '1006899144467-gorck5dhtftnjmtk3libd09risrqj0mc.apps.googleusercontent.com',
    iosClientId: '1006899144467-i2hlflfi5l484stk2363gq6t67iqboq0.apps.googleusercontent.com',
    iosBundleId: 'com.nasven.dheetantra',
  );
}
